development:
  secret_key_base: 03f5cedd10dc08eaad0f1a7fdd291c3cee12fc7069dd4797d6999b6c0cc9fa0eae1cac8f08c20890d20f69eb2dde3f3f60ccb59ae5134ab4e24d4bce0e3159bc
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_KEY_BASE"] %>
